version: '3.8'

services:
  db:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - blognet

  app:
    build: .
    depends_on:
      - db
    ports:
      - "80:8080"
    environment:
      - BLOG_UPLOAD-DIR
      - SPRING_DATASOURCE_URL
      - SPRING_DATASOURCE_USERNAME
      - SPRING_DATASOURCE_PASSWORD
      - SPRING_JPA_DATABASE-PLATFORM
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT-ID
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT-SECRET
    volumes:
      - uploads:/srv/images/
    networks:
      - blognet

volumes:
  postgres-data:
  uploads:

networks:
  blognet:
