version: '3.8'

services:
  db:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - blognet

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - BLOG_UPLOAD-DIR
      - SPRING_DATASOURCE_URL
      - SPRING_DATASOURCE_USERNAME
      - SPRING_DATASOURCE_PASSWORD
      - SPRING_JPA_DATABASE-PLATFORM
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT-ID
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT-SECRET
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT-ID
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT-SECRET
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_MICROSOFT_CLIENT-ID
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_MICROSOFT_CLIENT-SECRET
      - SPRING_THYMELEAF_CACHE
      - SPRING_WEB_RESOURCES_CACHE_PERIOD
      - SPRING_DEVTOOLS_RESTART_ENABLED
      - UMAMI_ENABLED
      - UMAMI_SCRIPT-URL
      - UMAMI_WEBSITE-ID
      - SPRING_MAIL_HOST
      - SPRING_MAIL_PORT
      - SPRING_MAIL_USERNAME
      - SPRING_MAIL_PASSWORD
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE
    volumes:
      - uploads:/srv/images/
      - ./src/main/resources/templates:/app/src/main/resources/templates
      - ./src/main/resources/static:/app/src/main/resources/static
    networks:
      - blognet

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - blognet

  umami-db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: ${UMAMI_DB_PASSWORD}
    volumes:
      - umami-postgres-data:/var/lib/postgresql/data
    networks:
      - blognet

  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    restart: always
    depends_on:
      - umami-db
    environment:
      DATABASE_URL: postgresql://umami:${UMAMI_DB_PASSWORD}@umami-db:5432/umami
      DATABASE_TYPE: postgresql
      APP_SECRET: ${UMAMI_APP_SECRET}
      HOSTNAME: ${UMAMI_HOSTNAME}
    networks:
      - blognet
    ports:
      - "3000:3000"

volumes:
  postgres-data:
  umami-postgres-data:
  uploads:
  caddy_data:
  caddy_config:

networks:
  blognet:
